{% set version = "0.6.0" %}

package:
  name: kiwipy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kiwipy/kiwipy-{{ version }}.tar.gz
  sha256: cd5cbc8eb5dca397066da0487b9a8a1821c2c7d8e07a899a42989a858ed944d0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - shortuuid
    - async_generator
    - pytray >=0.2.2,<0.3.0
    - deprecation
    # include dependencies for 'rmq' extra
    - aio-pika
    - pyyaml ~=5.1

test:
  imports:
    - kiwipy
    - kiwipy.rmq

about:
  home: https://github.com/aiidateam/kiwipy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python remote communications library
  description: |
    kiwipy is a library that makes remote messaging using RabbitMQ (and any
    other protocol for which a backend is written) EASY. I don't know about
    you but I find RabbitMQ HARD. It's all too easy to make a configuration
    mistake which is then difficult to debug. With kiwipy, there's none of
    this, just messaging, made simple, with all the nice properties and
    guarantees of AMQP.
  doc_url: https://github.com/aiidateam/kiwipy
  dev_url: https://github.com/aiidateam/kiwipy

extra:
  recipe-maintainers:
    - ltalirz
    - muhrin
    - sphuber
