{% set version = "0.8.4" %}

package:
  name: kiwipy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kiwipy/kiwipy-{{ version }}.tar.gz
  sha256: 625830fa07faac2c2a307bd3aa1caedac6596f37f9b9aba31b7f84c3d9c9f57a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=3.4,<4
  run:
    - python >=3.8
    - aio-pika ~=9.0
    - deprecation
    - pamqp ~=3.2
    - pytray >=0.3.4,<0.4.0
    # include dependencies for 'rmq' extra
    - pyyaml ~=6.0
    - shortuuid

test:
  imports:
    - kiwipy
    - kiwipy.rmq

about:
  home: https://github.com/aiidateam/kiwipy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A python remote communications library
  description: |
    kiwipy is a library that makes remote messaging using RabbitMQ (and any
    other protocol for which a backend is written) EASY. I don't know about
    you but I find RabbitMQ HARD. It's all too easy to make a configuration
    mistake which is then difficult to debug. With kiwipy, there's none of
    this, just messaging, made simple, with all the nice properties and
    guarantees of AMQP.
  doc_url: https://github.com/aiidateam/kiwipy
  dev_url: https://github.com/aiidateam/kiwipy

extra:
  recipe-maintainers:
    - ltalirz
    - muhrin
    - sphuber
    - chrisjsewell
